###
### GET Request
###

GET http://localhost:3000

###

###
### POST Request
###

POST http://localhost:3000/reservations
Content-Type: application/json

{
  "startDate": "12/20/2022",
  "endDate": "12/25/2022",
  "placeId": "12345",
  "invoiceId": "493",
}

###

###
### PUT Request
###

PUT https://api.example.com/users/123
Content-Type: application/json

{
  "name": "Updated Name",
  "email": "updatedemail@example.com"
}

###

###
### DELETE Request
###

DELETE https://api.example.com/users/123

###
